### ISSUE TITLE
Test failed

### ISSUE THREAD

**Issue by nahaivla** [duosecurity/duo_java#16]
com.duosecurity.duoweb.DuoWebException: Transaction has expired. Please check that the system time is correct

testVerifyResponse_whenValid

**Comment by xdesai** [comment]
Thanks for reporting! This is an issue with the unit tests using a response that expired as of last Sunday. I'll get a fix up shortly.

**Comment by nahaivla** [comment]
Thanks, will open issue again Sun Mar 17 2041 at 13:48:41 ))
