### ISSUE TITLE
Move artifact to maven central

### ISSUE THREAD

**Issue by nahaivla** [duosecurity/duo_java#19]
Hello, could you please build and upload version of duo_java to maven central. Thanks

**Comment by DuoKristina** [comment]
Hi @nahaivla ,

We encourage you to migrate to https://github.com/duosecurity/duo_universal_java, the updated Web SDK, which is in Maven https://search.maven.org/artifact/com.duosecurity/duo-universal-sdk/1.1.1/jar.

**Comment by AaronAtDuo** [comment]
As Kristina indicated, we recommend the new Duo Universal client, which is available on Maven.
