### ISSUE TITLE
Publishing DuoWeb on Maven Central

### ISSUE THREAD

**Issue by greatmazinger** [duosecurity/duo_java#5]
Not sure where else I can send this, so placing this here. I was wondering if you would be able to publish DuoWeb 1.3 on Maven Central.

**Comment by xdesai** [comment]
Hi Raoul!
This is something we are looking into doing. I don't have an exact timeline for this delivery, but I'll make a note that we need to come back and comment here with any updates. I'm gonna leave your issue open as a marker that this is also a request from our github community.

Thanks for using Duo and hopefully we'll be able to resolve this for you!

**Comment by mmoayyed** [comment]
Duplicate of https://github.com/duosecurity/duo_java/issues/1 ?

**Comment by greatmazinger** [comment]
From [this comment](https://github.com/duosecurity/duo_java/issues/1#issuecomment-182011983), it looks like there's no plan to publish to Maven Central. Is that still true (given that the comment was back in Feb 2016)?

**Comment by xdesai** [comment]
Ah my apologies! I had forgotten that #1 already existed.
That statement is correct that this is not currently on our roadmap for the next 6-9 months, but after that time we will re-evaluate our roadmap again and this will be considered (as it has the past couple of times).
Sorry, I'm not able to provide you anything more solid than that at this time!

One final thing I'd ask of you is to make sure that you do reach out to [Duo support](https://duo.com/support) and ask to be put on the feature request. That way we can make sure to reach out to you directly when any action on it is taken.

**Comment by ironcream** [comment]
+1.
Any updates on this one?

**Comment by AaronAtDuo** [comment]
Hi all,

Unfortunately, this is still not on our near-term roadmap.  We apologize for the inconvenience.

**Comment by DuoKristina** [comment]
We encourage you to migrate to https://github.com/duosecurity/duo_universal_java, the updated Web SDK, which is in Maven https://search.maven.org/artifact/com.duosecurity/duo-universal-sdk/1.1.1/jar.

**Comment by AaronAtDuo** [comment]
As Kristina indicated, we encourage use of the new Duo Universal client, which is available on Maven.
